// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview An AI agent that suggests a Lucide icon for a category.
 *
 * - suggestCategoryIcon - A function that suggests an icon name.
 * - SuggestCategoryIconInput - The input type for the suggestCategoryIcon function.
 * - SuggestCategoryIconOutput - The return type for the suggestCategoryIcon function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestCategoryIconInputSchema = z.object({
  categoryName: z
    .string()
    .describe(
      'The name of the category for which to suggest an icon.'
    ),
});
export type SuggestCategoryIconInput = z.infer<
  typeof SuggestCategoryIconInputSchema
>;

const SuggestCategoryIconOutputSchema = z.object({
  iconName: z
    .string()
    .describe(
      'The suggested icon name from the lucide-react library. Example: "Pizza".'
    ),
});
export type SuggestCategoryIconOutput = z.infer<
  typeof SuggestCategoryIconOutputSchema
>;

export async function suggestCategoryIcon(
  input: SuggestCategoryIconInput
): Promise<SuggestCategoryIconOutput> {
  return suggestCategoryIconFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestCategoryIconPrompt',
  input: {schema: SuggestCategoryIconInputSchema},
  output: {schema: SuggestCategoryIconOutputSchema},
  prompt: `You are a UI/UX expert. Your task is to suggest a suitable icon name from the 'lucide-react' icon library for a given food category name.

Return only the icon name in PascalCase. For example, for "Pizzas", you should return "Pizza". For "Bebidas", return "CupSoda". For "Carnes Rojas", return "Beef".

Category Name: {{{categoryName}}}`,
});

const suggestCategoryIconFlow = ai.defineFlow(
  {
    name: 'suggestCategoryIconFlow',
    inputSchema: SuggestCategoryIconInputSchema,
    outputSchema: SuggestCategoryIconOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
